// login page
import Head from 'next/head';
import axios from 'axios';
import Link from 'next/link';
import { useState } from 'react';
import { FaFacebook, FaGoogle } from 'react-icons/fa';

const Login = () => {
  // Form data
  const [formData, setFormData] = useState({
    email: '',
    password: '',
  });

  const [error, setError] = useState(null);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const response = await axios.post(
        'https://chimera-green.vercel.app/admins/login',
        formData
      );

      if (response.status === 200) {
        const { token, user } = response.data;

        localStorage.setItem('authToken', token);
        localStorage.setItem('userId', user._id);
        localStorage.setItem('userRole', user.role);

        // Redirect based on role
        if (user.role === 'admin') {
          window.location.href = `https://chimera-green.vercel.app/admins/${user._id}`;
        } else if (user.role === 'agent') {
          window.location.href = `https://chimera-green.vercel.app/${user._id}`;
        } else {
          window.location.href = `https://chimera-green.vercel.app/users/${user._id}`;
        }
      } else {
        setError(response.data.message || 'Login failed');
      }
    } catch (err) {
      console.error(err);
      setError('Internal server error');
    }
  };

  // Google OAuth
  const handleGoogleLogin = () => {
    window.location.href =
      'https://chimera-h56c.onrender.com/auth/google/login';
  };

  // Facebook OAuth
  const handleFacebookLogin = () => {
    const facebookOAuthURL =
      'https://chimera-h56c.onrender.com/auth/facebook/login';
    window.open(facebookOAuthURL, '_self');
  };

  return (
    <>
      <Head>
        <title>Chimera || Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>

      <div className="text-center py-5">
        <Link href="/" className="nav-item ">
          Back to menu
        </Link>
        <h2 className="fw-bold">Login to Your Account</h2>

        <form className="form text-center" onSubmit={handleSubmit}>
          <input
            className="form-control m-2 fw-bold"
            required
            type="email"
            name="email"
            placeholder="Enter Email"
            value={formData.email}
            onChange={handleChange}
          />
          <input
            className="form-control m-2 fw-bold"
            required
            type="password"
            name="password"
            placeholder="Enter Password"
            value={formData.password}
            onChange={handleChange}
          />

          <button className="w-100 btn btn-md" type="submit">
            Login
          </button>
          <h6 className="text-muted pt-3">or login with</h6>
          <ul className="nav justify-content-center list-unstyled d-flex pt-2">
            <li className="ms-3">
              <button
                className="text-muted bg-transparent border-0"
                onClick={handleFacebookLogin}
              >
                <FaFacebook className="social-icons m-2" />
              </button>
            </li>
            <li className="ms-3">
              <button
                className="text-muted bg-transparent border-0"
                onClick={handleGoogleLogin}
              >
                <FaGoogle className="social-icons m-2" />
              </button>
            </li>
          </ul>
          {error && <p style={{ color: 'red' }}>{error}</p>}
          <p className="pt-1 fw-bold">{"Don't have an account?"}</p>
          <Link className="btn btn-lg w-75" href="/register/register">
            Register
          </Link>
          <p className="mt-1 mb-3 text-muted">&copy; Chimera AI, 2024</p>
        </form>
      </div>
    </>
  );
};

export default Login;
