// resgiter page
import Link from 'next/link';
import Head from 'next/head';
import { useEffect } from 'react';
import Typewriter from 'typewriter-effect/dist/core';

const Register = () => {
  useEffect(() => {
    // Typewriter effect initialization
    const typewriter = new Typewriter('#typewriter', {
      strings: ['Welcome to Chimera AI', 'Revolutionizing Business Management'],
      autoStart: true,
      loop: true,
      delay: 75,
    });
  }, []);

  // Google registration function
  const handleGoogleRegister = () => {
    const googleOAuthURL = 'http://localhost:3001/auth/google/login';
    window.open(
      googleOAuthURL,
      'Google OAuth',
      'align-item-center',
      'width=300,height=300'
    );
  };

  return (
    <>
      <Head>
        <title>Chimera || Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className=" h-100">
        <div className="mt-5">
          <div className="container d-flex flex-wrap justify-content-center justify-content-lg-start mt-5">
            <div className=" pt-1 pt-md-4 pb-4">
              <div className=" justify-content-center">
                <Link className="text-center nav-link text-underlined" href="/">
                  back to menu
                </Link>
                <h1 className="text-center">Register</h1>
                <p className="text-center text-xl-start pb-3 mb-3">
                  Already have an account?{' '}
                  <Link className="text-dark" href="/login/login">
                    <small>login here</small>
                  </Link>
                </p>
                <hr className="my-4" />
                <ul className="nav justify-content-center list-unstyled d-flex pt-1 mt-3">
                  <li className="ms-3">
                    <button className="text-muted bg-transparent border-0">
                      <i className="social-icons fs-1 fa-brands fa-facebook mt-1"></i>
                    </button>
                  </li>
                  <li className="ms-3">
                    <button
                      className="text-muted bg-transparent border-0"
                      onClick={handleGoogleRegister}
                    >
                      <i className="social-icons fs-1 fa-brands fa-google mt-1"></i>
                    </button>
                  </li>
                </ul>
              </div>
            </div>
            <div className="w-100 align-self-end">
              <p className="nav d-block fs-xs text-center text-xl-start pb-2 mb-0">
                &copy;2024, All rights reserved.
                <Link
                  className="nav-link d-inline-block p-0"
                  href="/"
                  target="_blank"
                  rel="noopener"
                >
                  Chimera
                </Link>
              </p>
            </div>
          </div>

          {/* Background image with text */}
          <div
            className="position-relative mt-3 position-absolute top-0 end-0 w-50 d-none d-xl-block"
            style={{
              backgroundImage: 'url(../../images/hero/hero4.png)',
              height: '90vh',
              backgroundSize: 'cover',
              borderRadius: '10px',
              backgroundPosition: 'center',
              backgroundRepeat: 'no-repeat',
              boxShadow: '0 0 20px 0 rgb(0 0 0 / 30%)',
            }}
          >
            {/* Typing effect text */}
            <div
              id="typewriter"
              style={{
                position: 'absolute',
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)',
                color: 'white',
                textAlign: 'center',
                fontSize: '2rem',
                textShadow: '2px 2px 4px rgba(0, 0, 0, 0.7)',
              }}
            ></div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Register;

{
  /*
import Head from 'next/head';
import { useState, useEffect } from 'react';
import Link from 'next/link';

// metadata

const Register = () => {
  // Google registration function
  const handleGoogleRegister = () => {
    const googleOAuthURL = 'http://localhost:3001/auth/google/login';

    window.open(
      googleOAuthURL,
      'Google OAuth',
      'align-item-center',
      'width=300,height=300'
    );
  };

  // facebook registration function

  return (
    <>
      <Head>
        <title>Chimera || Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="text-center py-5 mt-5">
        <Link href="/" className="nav-item"></Link>
        <Link className="nav-link" href="/dashboard/dashboard/">
          Back to Dashboard
        </Link>
        <h1 className="fw-normal">Register</h1>

        <form className="form text-center py-5">
          <div className="container">
            <ul className="nav justify-content-center list-unstyled d-flex pt-2 ">
              <li className="ms-3">
                <button className="text-muted bg-transparent border-0">
                  <i className="social-icons fs-1 fa-brands fa-facebook mt-1"></i>
                </button>
              </li>
              <li className="ms-3">
                <button
                  className="text-muted bg-transparent border-0"
                  type="button"
                  onClick={handleGoogleRegister}
                >
                  <i className="social-icons fs-1 fa-brands fa-google mt-1"></i>
                </button>
              </li>
            </ul>
          </div>

          <div className="my-5">
            <p className="pt-1 fw-bold">{'Already have an account?'}</p>
            <Link className="btn btn lg w-75" href="/login/login/">
              Login
            </Link>
            <p className="mt-1 mb-3 text-muted">&copy; Chimera AI, 2024</p>
          </div>
        </form>
      </div>
    </>
  );
};

export default Register;
*/
}
