// sales page
import { useState } from 'react';
import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import Tab from '@/components/sales/Tab';
import Sidebar from '@/components/admin/Sidebar';
// overall revenue imports
import TopSelling from '@/components/sales/TopSelling';
import HourlyChart from '@/components/sales/HourlyChart';
import DailyChart from '@/components/sales/DailyChart';
import WeeklyChart from '@/components/sales/WeeklyChart';
import MonthlyChart from '@/components/sales/MonthlyChart';
// daily charts by category
import StarterDailyChart from '@/components/sales/starters/StarterDailyChart';
import HourlyDailyChart from '@/components/sales/starters/HourlyDailyChart';

export default function Sales() {
  const [activeComponent, setActiveComponent] = useState('Sales');

  const renderComponent = () => {
    switch (activeComponent) {
      // overall revenue
      case 'TopSelling':
        return <TopSelling setActiveComponent={setActiveComponent} />;
      case 'HourlyChart':
        return <HourlyChart setActiveComponent={setActiveComponent} />;
      case 'DailyChart':
        return <DailyChart setActiveComponent={setActiveComponent} />;
      case 'WeeklyChart':
        return <WeeklyChart setActiveComponent={setActiveComponent} />;
      // daily charts by category
      case 'StarterDailyChart':
        return <StarterDailyChart setActiveComponent={setActiveComponent} />;
      case 'HourlyDailyChart':
        return <HourlyDailyChart setActiveComponent={setActiveComponent} />;

      // default
      default:
        return <MonthlyChart />;
    }
  };
  return (
    <>
      <Head>
        <title>Sales</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout h-100">
        <Navbar />
        <Tab setActiveComponent={setActiveComponent} />
        <div className="container-fluid py-3">
          <div className="row mt-4">
            <div className="col-lg-4 col-xxl-3">
              <Sidebar setActiveComponent={setActiveComponent} />
            </div>

            <div className="col-lg-8 col-xxl-9">
              <div className="mt-3">{renderComponent()}</div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
