// messages page
import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import SideBar from '@/components/messages/SideBar';
import Chat from '@/components/messages/Chat';

export default function messages() {
  return (
    <>
      <Head>
        <title>Messages</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout h-100">
        <Navbar />
        <div className="container-fluid py-3">
          <div className="row">
            <div className="col-sm-8">
              <SideBar />
            </div>

            <div class="col-lg-8 col-xxl-9">
              <Chat />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
