// orders page
import { useState } from 'react';
import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import Tab from '@/components/orders/Tab';
import Sidebar from '@/components/admin/Sidebar';
import Today from '@/components/orders/Today';
import Yesterday from '@/components/orders/Yesterday';
import Weekly from '@/components/orders/Weekly';
import Monthly from '@/components/orders/Monthly';
import Refunds from '@/components/orders/Refunds';
//import Form from '@/components/orders/Form';

export default function Orders() {
  const [activeComponent, setActiveComponent] = useState('Orders');

  const renderComponent = () => {
    switch (activeComponent) {
      case 'Yesterday':
        return <Yesterday setActiveComponent={setActiveComponent} />;
      case 'Weekly':
        return <Weekly setActiveComponent={setActiveComponent} />;
      case 'Monthly':
        return <Monthly setActiveComponent={setActiveComponent} />;
      case 'Refunds':
        return <Refunds setActiveComponent={setActiveComponent} />;
      default:
        return <Today setActiveComponent={setActiveComponent} />;
    }
  };
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout h-100">
        <Navbar />
        <Tab />
        <div className="container-fluid ">
          <div className="row">
            <div className="col-lg-4 col-xxl-3">
              <Sidebar setActiveComponent={setActiveComponent} />
            </div>
            <div className="col-lg-8 col-xxl-9">{renderComponent()}</div>
          </div>
        </div>
      </div>
    </>
  );
}
