// Employee [id] page
import { useState, useEffect } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import Tab from '@/components/team/Tab';
//import Sidebar from '@/components/admin/Sidebar';
import Employees from '@/components/team/Employees';
//import Hosts from '@/components/team/Hosts';
//import Servers from '@/components/team/Servers';
//import Bar from '@/components/team/Bar';
//import Dish from '@/components/team/Dish';
//import Kitchen from '@/components/team/Kitchen';
//import Managers from '@/components/team/Managers';

export default function Team() {
  const router = useRouter();
  const { id } = router.query;
  const [employee, setEmployee] = useState([]);
  // employee
  useEffect(() => {
    if (id) {
      const fetchEmployeeData = async () => {
        try {
          const response = await axios.get(
            `http://localhost:3001/employees/${id}`
          );
          console.log('Employee data:', response.data);
          setEmployee(response.data);
        } catch (error) {
          console.error('Error fetching admin data:', error);
        }
      };

      fetchEmployeeData();
    }
  }, [id]);
  return (
    <>
      <Head>
        <title>Employees</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout h-100">
        <Navbar />
        <div>
          <Employees employees={employee} />
        </div>
      </div>
    </>
  );
}
