// Employee [id] page
import { useState, useEffect } from 'react';
import axios from 'axios';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import Photo from '@/components/team/Photo';
import Bio from '@/components/team/Bio';
import Nav from '@/components/team/Nav';
import Footer from '@/components/Nav/Footer';

export default function Team() {
  const router = useRouter();
  const { id } = router.query;
  const [employee, setEmployee] = useState([]);

  // employee
  useEffect(() => {
    if (id) {
      const fetchEmployeeData = async () => {
        try {
          const response = await axios.get(
            `https://chimera-h56c.onrender.com/employees/${id}`
          );
          console.log('Employee data:', response.data);
          setEmployee(response.data);
        } catch (error) {
          console.error('Error fetching admin data:', error);
        }
      };

      fetchEmployeeData();
    }
  }, [id]);
  return (
    <>
      <Head>
        <title>Team</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout h-100">
        <Navbar />
        <div className="container-fluid">
          <Nav />
        </div>
        <div className="container-fluid">
          <div className="row py-4">
            <div className="col-md-6">
              <h3 className="mt-2">{employee.name}</h3>
              <div className="d-flex mt-3">
                <Photo employees={employee} />
              </div>
            </div>
            <div className="col-md-6">
              <h3 className="text-center fs-1 fw-bold ">Bio</h3>

              <div className="mt-2">
                <Bio employees={employee} />
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
