// reports page
import { useState } from 'react';
import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import Tab from '@/components/reports/Tab';
import Starters from '@/components/reports/Starters';
import Entrees from '@/components/reports/Entrees';
import Desserts from '@/components/reports/Desserts';
import Bar from '@/components/reports/Bar';

export default function Reports() {
  const [activeComponent, setActiveComponent] = useState('Reports');

  const renderComponent = () => {
    switch (activeComponent) {
      case 'Entrees':
        return <Entrees setActiveComponent={setActiveComponent} />;
      case 'Desserts':
        return <Desserts setActiveComponent={setActiveComponent} />;
      case 'Bar':
        return <Bar setActiveComponent={setActiveComponent} />;
      default:
        return <Starters setActiveComponent={setActiveComponent} />;
    }
  };
  return (
    <>
      <Head>
        <title>Reports</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout h-100">
        <Navbar />
        <Tab setActiveComponent={setActiveComponent} />
        <div>{renderComponent()}</div>
      </div>
    </>
  );
}
