// profile page
import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import Cover from '@/components/profile/Cover';
import Sidebar from '@/components/profile/Sidebar';

export default function profile() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout h-100">
        <Navbar />
        <Cover />
        <div className="container-fluid py-3">
          <div className="row">
            <div className="col-lg-4 col-xxl-3">
              <Sidebar />
            </div>
            <div className="col-lg-8 col-xxl-9">
              <h1>Test</h1>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
