// inventory page
import { useState } from 'react';
import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import Tab from '@/components/inventory/Tab';
import Sidebar from '@/components/admin/Sidebar';
import Produce from '@/components/inventory/Produce';
import Dairy from '@/components/inventory/Dairy';
import Proteins from '@/components/inventory/Proteins';
import Beverages from '@/components/inventory/Beverages';
import Dry from '@/components/inventory/Dry';
import Paper from '@/components/inventory/Paper';

export default function Inventory() {
  const [activeComponent, setActiveComponent] = useState('Inventory');

  const renderComponent = () => {
    switch (activeComponent) {
      case 'Dairy':
        return <Dairy setActiveComponent={setActiveComponent} />;
      case 'Proteins':
        return <Proteins setActiveComponent={setActiveComponent} />;
      case 'Beverages':
        return <Beverages setActiveComponent={setActiveComponent} />;
      case 'Dry':
        return <Dry setActiveComponent={setActiveComponent} />;
      case 'Paper':
        return <Paper setActiveComponent={setActiveComponent} />;
        // chart analytics
        {
          /*
      case 'HourlyChart':
        return <HourlyChart setActiveComponent={setActiveComponent} />;
      case 'DayilyChart':
        return <DailyChart setActiveComponent={setActiveComponent} />;
      case 'WeeklytChart':
        return <WeeklyChart setActiveComponent={setActiveComponent} />;
      case 'MonthlyChart':
        return <MonthlyChart setActiveComponent={setActiveComponent} />;
      default:
        return <Starters setActiveComponent={setActiveComponent} />;

    */
        }
      default:
        return <Produce setActiveComponent={setActiveComponent} />;
    }
  };
  return (
    <>
      <Head>
        <title>Inventory</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout h-100">
        <Navbar />
        <Tab setActiveComponent={setActiveComponent} />
        <div className="container-fluid ">
          <div className="row">
            <div className="col-lg-4 col-xxl-3">
              <Sidebar setActiveComponent={setActiveComponent} />
            </div>
            <div className="col-lg-8 col-xxl-9">{renderComponent()}</div>
          </div>
        </div>
      </div>
    </>
  );
}
