// menu page
import Link from 'next/link';
import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import Header from '@/components/menu/Header';
import Footer from '@/components/Nav/Footer';
import Tech from '@/components/menu/Tech';
import Details from '@/components/menu/Details';
import Industries from '@/components/menu/Industries';
import Banner from '@/components/menu/Banner';

export default function menu() {
  return (
    <>
      <Head>
        <title>Chimera || Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout h-100">
        <Navbar />
        <Header />
        <div className=" pt-5">
          <Industries />
        </div>
        <div className=" pt-5">
          <Tech />
        </div>
        <div className=" pt-5">
          <Details />
        </div>
        <div className=" pt-5">
          <Banner />
        </div>
        <div className="pt-5 mt-5">
          <Footer />
        </div>
      </div>
    </>
  );
}
