import Head from 'next/head';
import Navbar from '@/components/Nav/Navbar';
import Bookings from '@/components/calendar/Bookings';
import Chart from '@/components/charts/chart';
import DayChart from '@/components/charts/DayChart';
import Revenue from '@/components/charts/Revenue';
import TopSeller from '@/components/charts/TopSeller';
import Totals from '@/components/charts/Totals';
import Activity from '@/components/messages/Activity';

export default function dashboard() {
  return (
    <>
      <Head>
        <title>Chimera</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Frijole&family=Teko:wght@300&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.1.1/css/all.css"
        />
      </Head>
      <div className="layout">
        <Navbar />
        <div className="container-fluid py-3">
          <div className="row">
            <div className="col-sm-8">
              <h1>Greetings!</h1>
            </div>
            <div className="col-sm-4">
              <Bookings />
            </div>
          </div>
          {/*revenue cards */}
          <div className="row mt-4">
            <div className="col-lg-6">
              <div className="row">
                <div className="col-6 col-sm-6 mb-3">
                  {/*card start */}
                  <div className="card">
                    <div className="card-body">
                      <div className="float-end">
                        <i className="mdi widget-icon"></i>
                      </div>
                      <h5 className="text-muted fw-normal mt-0">Customers</h5>
                      <h3 className="mt-3 mb-3">9,210</h3>
                      <p className="mb-0 text-muted">
                        <span className="me-2">
                          <i className="card-icon fa-solid fa-arrow-up"></i>
                          544%
                        </span>
                        <span className="text-nowrap">Last Month</span>
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-6 col-sm-6 mb-3">
                  <div className="card">
                    <div className="card-body">
                      <div className="float-end">
                        <i className="mdi widget-icon"></i>
                      </div>
                      <h5 className="text-muted fw-normal mt-0">Orders</h5>
                      <h3 className="mt-3 mb-3">8,500</h3>
                      <p className="mb-0 text-muted">
                        <span className="me-2">
                          <i className="card-icon fa-solid fa-arrow-up"></i>
                          400%
                        </span>
                        <span className="text-nowrap">Last Month</span>
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-6 col-sm-6 mb-3">
                  <div className="card">
                    <div className="card-body">
                      <div className="float-end">
                        <i className="mdi widget-icon"></i>
                      </div>
                      <h1 className="text-muted fw-normal mt-0 fs-4">
                        Revenue
                      </h1>
                      <h3 className="mt-3 mb-3">$120K</h3>
                      <p className="mb-0 text-muted">
                        <span className="me-2">
                          <i className="card-icon fa-solid fa-arrow-up"></i>
                          25%
                        </span>
                        <span className="text-nowrap">Last Month</span>
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-6 col-sm-6 mb-3">
                  <div className="card">
                    <div className="card-body">
                      <div className="float-end">
                        <i className="mdi widget-icon"></i>
                      </div>
                      <h5 className="text-muted fw-normal mt-0">Growth</h5>
                      <h3 className="mt-3 mb-3">15%</h3>
                      <p className="mb-0 text-muted">
                        <span className="me-2">
                          <i className="card-icon fa-solid fa-arrow-up"></i>
                          5%
                        </span>
                        <span className="text-nowrap">Last Month</span>
                      </p>
                    </div>
                  </div>

                  {/* card end */}
                </div>
              </div>
            </div>
            {/*revenue chart */}
            <div className="col-lg-6">
              <div className="">
                <div className="">
                  <Chart />
                </div>
              </div>
            </div>
          </div>
          {/*revenue*/}
          <div className=" py-5">
            <div className="row">
              <div className="col-lg-8 d-flex flex-column justify-content-center">
                <Revenue />
              </div>
              <div className="col-lg-4 d-flex flex-column justify-content-center">
                <div className="">
                  <DayChart />
                </div>
              </div>
            </div>
            {/*sales by hour */}
          </div>
          {/*top sales */}
          <div className="row">
            <div className="col-xl-6 col-lg-12 order-lg-2 order-xl-1">
              <TopSeller />
            </div>
            <div className="col-xl-3 col-lg-6 order-lg-1">
              <Totals />
            </div>
            <div className="col-xl-3 col-lg-6 order-lg-1">
              <Activity />
            </div>
          </div>
          {/*sales by hour */}
        </div>
      </div>
    </>
  );
}
